// Plugin identity metadata read by RhinoCommon.
// Most attributes (Title / Company / Version) are generated by the SDK
// from the .csproj. We only declare the ones Rhino needs that the SDK
// doesn't provide — the plugin GUID + rich descriptions.

using System.Runtime.InteropServices;
using Rhino.PlugIns;

// Unique plugin id — must match what Rhino uses to identify the plugin.
// Real random UUIDv4 (was a placeholder UUIDv7 pattern that some
// loaders reject when validating version bits).
[assembly: Guid("cb47750c-49dd-442e-a5f4-53217755539a")]

// PlugInDescription fills the "About" box in Rhino's plugin manager
[assembly: PlugInDescription(DescriptionType.Organization, "ARIA-OS")]
[assembly: PlugInDescription(DescriptionType.WebSite,      "")]
