// Plugin identity metadata read by RhinoCommon.
// Most attributes (Title / Company / Version) are generated by the SDK
// from the .csproj. We only declare the ones Rhino needs that the SDK
// doesn't provide — the plugin GUID + rich descriptions.

using System.Runtime.InteropServices;
using Rhino.PlugIns;

// Unique plugin id — must match what Rhino uses to identify the plugin
[assembly: Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890")]

// PlugInDescription fills the "About" box in Rhino's plugin manager
[assembly: PlugInDescription(DescriptionType.Organization, "ARIA-OS")]
[assembly: PlugInDescription(DescriptionType.WebSite,      "")]
