// Plugin identity metadata read by RhinoCommon.
// Most attributes (Title / Company / Version) are generated by the SDK
// from the .csproj. We only declare the ones Rhino needs that the SDK
// doesn't provide — the plugin GUID + rich descriptions.

using System.Runtime.InteropServices;
using Rhino.PlugIns;

// Unique plugin id — must match what Rhino uses to identify the plugin.
// Real random UUIDv4. Bumped 2x: first from a placeholder UUIDv7
// pattern, then again because Rhino had cached the previous GUID
// from a failed-load attempt with stale path metadata. If you change
// this again you MUST first disable+remove the old AriaPanel entry
// from Rhino's Plug-ins manager (Tools → Options → Plug-ins).
[assembly: Guid("6a1966a7-be24-4814-8066-47393d3c1806")]

// PlugInDescription fills the "About" box in Rhino's plugin manager
[assembly: PlugInDescription(DescriptionType.Organization, "ARIA-OS")]
[assembly: PlugInDescription(DescriptionType.WebSite,      "")]
