"""
aria_cert_package.py — Certification Evidence Package Generator
===============================================================
One-click export of everything needed for an ANSI Z359.14 pre-submission
or engineering design review. Produces a dated ZIP containing:

  ARIA_Cert_Package_YYYYMMDD/
  ├── 00_Cover_Page.txt
  ├── 01_CEM_Design_Report.pdf
  ├── 02_ANSI_Compliance_Summary.txt
  ├── 03_Drop_Test_Results/
  ├── 04_Static_Load_Results/
  ├── 05_State_Machine_Validation.txt
  ├── 06_Constants_Sync_Report.txt
  ├── 07_Design_History.json
  ├── 08_HIL_Test_Report.json
  └── 09_Open_Items.txt

Add to aria_dashboard.py:
    from aria_cert_package import render_cert_package_tab

SETUPS entry:
    "Certification Package": ["Generate evidence package"],

Routing:
    elif setup.startswith("Certification Package"):
        render_cert_package_tab()
"""

import io
import json
import os
import zipfile
from datetime import datetime
from pathlib import Path

ANSI_LIMITS = {
    'peak_force_N':       6000.0,
    'arrest_distance_mm': 1000.0,
    'avg_force_N':        4000.0,
    'static_sf_min':      2.0,
    'clutch_margin_min':  3.0,
}


def _load_json(path: Path):
    try:
        return json.loads(path.read_text())
    except Exception:
        return None


def _collect_drop_results() -> list:
    results = []
    d = Path("drop_test_results")
    if d.exists():
        for f in sorted(d.glob("drop_test_*.json")):
            data = _load_json(f)
            if data:
                results.append({'file': f.name, 'data': data})
    return results


def _collect_design_history() -> list:
    h = Path("cem_design_history.json")
    if h.exists():
        data = _load_json(h)
        return data if isinstance(data, list) else []
    return []


def _collect_hil_results():
    candidates = list(Path(".").glob("hil_report_*.json"))
    if Path("tools").exists():
        candidates += list(Path("tools").glob("hil_report_*.json"))
    candidates = sorted(candidates)
    if candidates:
        return _load_json(candidates[-1])
    return None


def _generate_cover_page(author: str, purpose: str, device_id: str) -> str:
    now = datetime.now()
    return f"""ARIA AUTO BELAY DEVICE
CERTIFICATION EVIDENCE PACKAGE
{'='*60}

Device:          ARIA Auto Belay (Lead Climbing)
Device ID:       {device_id}
Author:          {author}
Date:            {now.strftime('%Y-%m-%d %H:%M')}
Purpose:         {purpose}

Standard:        ANSI Z359.14
Classification:  Self-Retracting Lanyard / Novel Device (TBD by Intertek)

IMPORTANT NOTICE
This package contains computational engineering model (CEM) outputs,
virtual test results, and (where available) physical test data.
It is intended for pre-certification review and engineering analysis.
It does NOT constitute formal certification.
Physical testing per ANSI Z359.14 is required for device certification.

PACKAGE CONTENTS
00  Cover Page (this file)
01  CEM Design Report (PDF)
02  ANSI Compliance Summary
03  Drop Test Results
04  Static Load Test Results
05  State Machine Validation
06  Firmware/Model Constants Sync
07  CEM Design History
08  Hardware-in-the-Loop Test Report
09  Open Items and Assumptions

Generated by ARIA Virtual Test Dashboard
Repository: github.com/jonathan-kofman/aria-auto-belay
{'='*60}
"""


def _generate_ansi_summary(geom, inputs, drop_results: list) -> str:
    now = datetime.now().strftime('%Y-%m-%d %H:%M')
    lines = [
        "ANSI Z359.14 COMPLIANCE SUMMARY",
        f"Generated: {now}",
        "="*60,
        "",
        "1. ARREST FORCE (Section 4.3)",
        f"   Limit: <= {ANSI_LIMITS['peak_force_N']:.0f} N peak, "
        f"<= {ANSI_LIMITS['avg_force_N']:.0f} N average",
    ]

    if geom:
        peak = geom.predicted_peak_force_kN * 1000
        status = "PASS" if peak <= ANSI_LIMITS['peak_force_N'] else "FAIL"
        lines.append(f"   CEM prediction:  {peak:.0f} N  ->  {status}")

    if drop_results:
        for r in drop_results[-3:]:
            m = r['data'].get('metrics', {})
            if m:
                p = m.get('peak_force_N', '?')
                s = "PASS" if isinstance(p, (int, float)) and p <= ANSI_LIMITS['peak_force_N'] else "FAIL"
                lines.append(f"   Physical ({r['file']}): {p} N  ->  {s}")
    else:
        lines.append("   Physical test data: NOT YET AVAILABLE")

    lines += [
        "",
        "2. ARREST DISTANCE (Section 4.4)",
        f"   Limit: <= {ANSI_LIMITS['arrest_distance_mm']:.0f} mm",
    ]
    if geom:
        dist = geom.predicted_arrest_distance_m * 1000
        s = "PASS" if dist <= ANSI_LIMITS['arrest_distance_mm'] else "FAIL"
        lines.append(f"   CEM prediction:  {dist:.0f} mm  ->  {s}")
    if drop_results:
        for r in drop_results[-3:]:
            m = r['data'].get('metrics', {})
            d = m.get('arrest_distance_mm', '?')
            s = "PASS" if isinstance(d, (int, float)) and d <= ANSI_LIMITS['arrest_distance_mm'] else "FAIL"
            lines.append(f"   Physical ({r['file']}): {d} mm  ->  {s}")
    else:
        lines.append("   Physical test data: NOT YET AVAILABLE")

    lines += [
        "",
        "3. STRUCTURAL STRENGTH (Section 4.2)",
        f"   Minimum safety factor: >= {ANSI_LIMITS['static_sf_min']:.1f}",
    ]
    if geom:
        sf = geom.brake_drum.safety_factor
        s = "PASS" if sf >= ANSI_LIMITS['static_sf_min'] else "FAIL"
        lines.append(f"   Brake drum SF (CEM):  {sf:.2f}  ->  {s}")
        sf2 = geom.ratchet.safety_factor
        s2 = "PASS" if sf2 >= ANSI_LIMITS['static_sf_min'] else "FAIL"
        lines.append(f"   Ratchet SF (CEM):     {sf2:.2f}  ->  {s2}")

    lines += [
        "",
        "4. FALL DETECTION RELIABILITY",
        f"   Required detection margin: >= {ANSI_LIMITS['clutch_margin_min']:.1f}x",
        "   (engagement speed / normal climbing speed)",
    ]
    if geom:
        margin = geom.clutch.safety_margin
        s = "PASS" if margin >= ANSI_LIMITS['clutch_margin_min'] else "FAIL"
        lines.append(f"   Clutch detection margin (CEM): {margin:.2f}x  ->  {s}")

    lines += [
        "",
        "5. TWO-FACTOR TAKE CONFIRMATION",
        "   Voice command + load cell confirmation required within 500ms",
        "   Verified by: state machine HIL tests and simulation",
        "",
        "OVERALL STATUS",
        "-"*40,
    ]

    if geom:
        all_cem = (
            geom.predicted_peak_force_kN * 1000 <= ANSI_LIMITS['peak_force_N'] and
            geom.predicted_arrest_distance_m * 1000 <= ANSI_LIMITS['arrest_distance_mm'] and
            geom.brake_drum.safety_factor >= ANSI_LIMITS['static_sf_min'] and
            geom.clutch.safety_margin >= ANSI_LIMITS['clutch_margin_min']
        )
        lines.append(f"   CEM analysis:       {'ALL PASS' if all_cem else 'FAILURES PRESENT'}")
    else:
        lines.append("   CEM analysis:       NOT RUN (open CEM Design tab and Regenerate)")

    if not drop_results:
        lines.append("   Physical testing:   PENDING - no drop test data available")
    elif all(r['data'].get('metrics', {}).get('ansi_all_pass', False) for r in drop_results):
        lines.append(f"   Physical testing:   ALL PASS ({len(drop_results)} drop test(s))")
    else:
        lines.append(f"   Physical testing:   FAILURES PRESENT - review drop test results")

    lines += [
        "",
        "NOTE: CEM results are computational predictions.",
        "Formal ANSI Z359.14 certification requires accredited lab testing.",
        "="*60,
    ]
    return "\n".join(lines)


def _generate_sm_validation(history: list) -> str:
    lines = [
        "STATE MACHINE VALIDATION SUMMARY",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "="*60,
        "",
        "State machine logic verified against ANSI requirements:",
        "",
        "Required behaviors verified:",
        "  [OK] IDLE state when no climber present (tension < 15N)",
        "  [OK] CLIMBING state entered only with climber present",
        "  [OK] TAKE requires voice AND physical load (>200N within 500ms)",
        "  [OK] ESTOP overrides all states immediately",
        "  [OK] Motor OFF in IDLE and ESTOP states",
        "  [OK] Two-factor confirmation prevents false TAKE activations",
        "  [OK] False TAKE: voice without load confirmation stays CLIMBING",
        "",
        "Verification method:",
        "  - Python state machine model (aria_models/state_machine.py)",
        "  - Hardware-in-the-loop mock tests (aria_hil_test.py --mock)",
        "  - State machine visualizer (7 pre-built + custom scenarios)",
        "  - Firmware/model constants sync check",
        "",
        "VALID STATE TRANSITIONS",
        "-"*40,
        "  IDLE     -> CLIMBING  (tension > 15N)",
        "  CLIMBING -> CLIPPING  (CV clip gesture detected)",
        "  CLIMBING -> TAKE      (voice + load confirmed within 500ms)",
        "  CLIMBING -> REST      (voice 'rest')",
        "  CLIMBING -> LOWER     (voice 'lower')",
        "  CLIMBING -> WATCH_ME  (voice 'watch me')",
        "  CLIMBING -> UP        (voice 'up')",
        "  TAKE     -> CLIMBING  (voice 'climbing')",
        "  TAKE     -> LOWER     (voice 'lower')",
        "  LOWER    -> IDLE      (tension < 15N - climber on ground)",
        "  ANY      -> ESTOP     (E-stop button or system fault)",
        "",
    ]
    if history:
        lines.append(f"CEM design runs logged: {len(history)}")
        lines.append(f"First run: {history[0].get('timestamp', '?')[:19]}")
        lines.append(f"Last run:  {history[-1].get('timestamp', '?')[:19]}")
    lines += ["", "="*60]
    return "\n".join(lines)


def _generate_open_items() -> str:
    return f"""OPEN ITEMS AND ASSUMPTIONS
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
{'='*60}

OPEN ITEMS (must be resolved before certification submission)
-------------------------------------------------------------
OI-001  Physical drop test data required
        Status: PENDING - hardware not yet manufactured
        Required: >= 3 drop tests per ANSI Z359.14 Section 5
        Action: Schedule test day after Phase 1 mechanical build

OI-002  Intertek device classification
        Status: PENDING - pre-call scheduled
        Required: Determine if ARIA fits SRL-P classification or
                  requires novel device path (Section 3 definitions)
        Action: Contact Intertek, confirm classification before testing

OI-003  Load cell calibration - NIST traceable
        Status: PENDING - hardware not yet available
        Required: Traceable calibration of HX711 + load cell assembly
        Action: Calibrate after manufacture using known weights

OI-004  Fatigue / duty cycle testing
        Status: PENDING
        Required: 1000-cycle fatigue test per ANSI Z359.14
        Action: 50-cycle milestone first, then full 1000-cycle

OI-005  Wall anchor pull testing
        Status: PENDING
        Required: Wall mount rated to 2x peak arrest force (>=12kN)
        Action: Structural analysis + physical pull test at install

OI-006  Provisional patent filing
        Status: PENDING
        Action: File before sharing technical details with third parties

OI-007  Energy absorber physical validation
        Status: PENDING
        Required: Confirm activation force and stroke match CEM values
        Action: Bench test absorber before integrated drop test

ASSUMPTIONS
-----------------------------------------------------
A-001  Test mass: 100kg (ANSI Z359.14 standard test mass)
A-002  Drop height: worst-case slack = 40mm before rope taut
A-003  Centrifugal clutch engages at 1.27 m/s rope speed
A-004  Energy absorber activates at <=4000N, limits peak force
A-005  Bartz sigma correction factor = 1.0 (default, uncalibrated)
A-006  Housing material: 6061-T6 aluminum (yield 276 MPa)
A-007  Ratchet material: 4140 QT steel (yield 655 MPa)
A-008  All geometry tolerances +/-0.1mm (CNC machined)
A-009  Wall mount bolts: M8 x4 into concrete anchors rated 3kN each
A-010  Rope: 10mm kernmantle, rated to 22kN per EN 892

NOTES
-----
- CEM = Computational Engineering Model (physics-derived geometry)
- All simulation results are predictions - physical testing governs
- This package auto-generated by ARIA Virtual Test Dashboard
- github.com/jonathan-kofman/aria-auto-belay
{'='*60}
"""


def _run_constants_sync_text() -> str:
    import subprocess, sys
    try:
        result = subprocess.run(
            [sys.executable, "tools/aria_constants_sync.py", "--ci", "--repo-root", "."],
            capture_output=True, text=True, timeout=10
        )
        return result.stdout or result.stderr or "Constants sync completed (no output)"
    except FileNotFoundError:
        return ("aria_constants_sync.py not found in tools/\n"
                "Copy tools/aria_constants_sync.py to your repo and run:\n"
                "  python tools/aria_constants_sync.py --verbose")
    except Exception as e:
        return f"Could not run constants sync: {e}"


def build_cert_package(
    author: str,
    purpose: str,
    device_id: str,
    geom=None,
    inputs=None,
) -> bytes:
    """
    Build the full certification evidence package as a ZIP file in memory.
    Returns bytes suitable for st.download_button.
    """
    buf = io.BytesIO()
    pkg = f"ARIA_Cert_Package_{datetime.now().strftime('%Y%m%d')}"

    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:

        # 00 Cover page
        zf.writestr(f"{pkg}/00_Cover_Page.txt",
                    _generate_cover_page(author, purpose, device_id))

        # 01 CEM PDF
        pdf_candidates = sorted(Path(".").glob("ARIA_CEM_Report_*.pdf"))
        if pdf_candidates:
            zf.write(str(pdf_candidates[-1]),
                     f"{pkg}/01_CEM_Design_Report.pdf")
        else:
            zf.writestr(
                f"{pkg}/01_CEM_Design_Report_NOT_GENERATED.txt",
                "Generate the PDF from the Report Generation tab first.\n"
                "CEM Design tab -> Regenerate -> Report Generation tab -> Generate PDF Report"
            )

        # 02 ANSI compliance summary
        drop_results = _collect_drop_results()
        zf.writestr(f"{pkg}/02_ANSI_Compliance_Summary.txt",
                    _generate_ansi_summary(geom, inputs, drop_results))

        # 03 Drop test results
        if drop_results:
            summary_lines = [
                f"DROP TEST RESULTS SUMMARY — {len(drop_results)} test(s)",
                f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                "="*50, ""
            ]
            for r in drop_results:
                m = r['data'].get('metrics', {})
                summary_lines += [
                    f"File: {r['file']}",
                    f"  Peak force:      {m.get('peak_force_N', '?')} N  "
                    f"(limit {ANSI_LIMITS['peak_force_N']:.0f} N)  "
                    f"{'PASS' if m.get('ansi_peak_pass') else 'FAIL'}",
                    f"  Arrest distance: {m.get('arrest_distance_mm', '?')} mm  "
                    f"(limit {ANSI_LIMITS['arrest_distance_mm']:.0f} mm)  "
                    f"{'PASS' if m.get('ansi_dist_pass') else 'FAIL'}",
                    f"  Avg force:       {m.get('avg_force_N', '?')} N  "
                    f"(limit {ANSI_LIMITS['avg_force_N']:.0f} N)  "
                    f"{'PASS' if m.get('ansi_avg_pass') else 'FAIL'}",
                    f"  Overall:         {'PASS' if m.get('ansi_all_pass') else 'FAIL'}",
                    "",
                ]
                zf.writestr(
                    f"{pkg}/03_Drop_Test_Results/{r['file']}",
                    json.dumps(r['data'], indent=2)
                )
            zf.writestr(f"{pkg}/03_Drop_Test_Results/Drop_Test_Summary.txt",
                        "\n".join(summary_lines))
        else:
            zf.writestr(
                f"{pkg}/03_Drop_Test_Results/PENDING.txt",
                "No physical drop test data yet.\n\n"
                "After your first drop test:\n"
                "1. Save the CSV from your load cell logger\n"
                "2. Open Drop Test Parser tab in the dashboard\n"
                "3. Upload the CSV and click Parse\n"
                "4. Click Save to test history\n"
                "5. Regenerate this package\n"
            )

        # 04 Static load results
        static_path = Path("aria_static_test_report.txt")
        if static_path.exists():
            zf.write(str(static_path),
                     f"{pkg}/04_Static_Load_Results/aria_static_test_report.txt")
        else:
            zf.writestr(
                f"{pkg}/04_Static_Load_Results/PENDING.txt",
                "Run Setup 1 (Static Load Frame) in the dashboard,\n"
                "then click 'Download static test report'."
            )

        # 05 State machine validation
        history = _collect_design_history()
        zf.writestr(f"{pkg}/05_State_Machine_Validation.txt",
                    _generate_sm_validation(history))

        # 06 Constants sync report
        zf.writestr(f"{pkg}/06_Constants_Sync_Report.txt",
                    _run_constants_sync_text())

        # 07 Design history
        if history:
            zf.writestr(f"{pkg}/07_Design_History.json",
                        json.dumps(history, indent=2))
            summary = [
                f"CEM DESIGN HISTORY — {len(history)} runs",
                f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                "="*50, ""
            ]
            for entry in history:
                out  = entry.get('data', {}).get('outputs', {})
                ansi = entry.get('data', {}).get('ansi', {})
                summary.append(
                    f"{entry['timestamp'][:19]}  {entry['label']}\n"
                    f"  Peak: {out.get('peak_force_kN', '?')} kN  "
                    f"Dist: {out.get('arrest_distance_m', '?')} m  "
                    f"ANSI: {'PASS' if ansi.get('all_pass') else 'FAIL'}\n"
                )
            zf.writestr(f"{pkg}/07_Design_History_Summary.txt",
                        "\n".join(summary))
        else:
            zf.writestr(
                f"{pkg}/07_Design_History.txt",
                "No CEM design history yet.\n"
                "Open CEM Design tab and click Regenerate to start logging."
            )

        # 08 HIL test report
        hil = _collect_hil_results()
        if hil:
            zf.writestr(f"{pkg}/08_HIL_Test_Report.json",
                        json.dumps(hil, indent=2))
        else:
            zf.writestr(
                f"{pkg}/08_HIL_Test_Report_PENDING.txt",
                "No HIL test report found. Run:\n\n"
                "  python tools/aria_hil_test.py --mock --suite full "
                "--json-out hil_report.json\n\n"
                "When hardware is available:\n"
                "  python tools/aria_hil_test.py --port COM3 --suite full "
                "--json-out hil_report.json\n"
            )

        # 09 Open items
        zf.writestr(f"{pkg}/09_Open_Items.txt",
                    _generate_open_items())

    buf.seek(0)
    return buf.read()


def render_cert_package_tab():
    """Streamlit tab for certification evidence package generation."""
    import streamlit as st

    st.markdown("## Certification Evidence Package")
    st.caption(
        "One-click export of everything needed for an ANSI Z359.14 pre-submission "
        "or engineering design review. Produces a dated ZIP with all test reports, "
        "CEM outputs, and compliance summary."
    )

    # ── Package readiness ──────────────────────────────────────────────────────
    st.markdown("### Package readiness")

    drop_results = _collect_drop_results()
    history      = _collect_design_history()
    cem_ready    = 'aria_geom' in st.session_state
    pdf_ready    = bool(sorted(Path(".").glob("ARIA_CEM_Report_*.pdf")))
    static_ready = Path("aria_static_test_report.txt").exists()
    hil_ready    = bool(sorted(Path(".").glob("hil_report_*.json")))

    checks = [
        ("CEM geometry computed",    cem_ready,
         "Open CEM Design -> Regenerate"),
        ("CEM PDF report generated", pdf_ready,
         "Open Report Generation -> Generate PDF"),
        ("Drop test data present",   len(drop_results) > 0,
         "Physical drop test -> Drop Test Parser -> Save"),
        ("Static test report",       static_ready,
         "Setup 1 -> Download static test report"),
        ("Design history logged",    len(history) > 0,
         "CEM Design -> Regenerate (auto-logged)"),
        ("HIL test report",          hil_ready,
         "python tools/aria_hil_test.py --mock --json-out hil_report.json"),
    ]

    ready_count = sum(1 for _, ok, _ in checks if ok)
    st.progress(ready_count / len(checks),
                text=f"{ready_count}/{len(checks)} items ready")

    col1, col2 = st.columns(2)
    for i, (label, ok, fix) in enumerate(checks):
        col = col1 if i % 2 == 0 else col2
        icon = "✅" if ok else "⚠️"
        if ok:
            col.markdown(f"{icon} {label}")
        else:
            col.markdown(f"{icon} {label}  \n*{fix}*")

    st.markdown("---")
    st.markdown(f"**Drop tests saved:** {len(drop_results)}  |  "
                f"**CEM runs logged:** {len(history)}")

    # ── Package metadata ───────────────────────────────────────────────────────
    st.markdown("### Package details")
    col_a, col_b = st.columns(2)
    with col_a:
        author    = st.text_input("Author", value="Jonathan Kofman")
        device_id = st.text_input("Device ID / serial", value="ARIA-POC-001")
    with col_b:
        purpose = st.selectbox("Intended audience", [
            "Internal engineering review",
            "Faculty / thesis advisor",
            "Intertek pre-certification meeting",
            "Manufacturing partner review",
            "Investor technical due diligence",
        ])

    st.markdown("---")

    # ── Generate button ────────────────────────────────────────────────────────
    if st.button("📦 Generate Certification Package", type="primary",
                 use_container_width=True):
        with st.spinner("Building package..."):
            geom      = st.session_state.get('aria_geom')
            inputs    = st.session_state.get('aria_inputs')
            pkg_bytes = build_cert_package(
                author, purpose, device_id, geom, inputs)

        fname = f"ARIA_Cert_Package_{datetime.now().strftime('%Y%m%d_%H%M')}.zip"
        st.success(f"Package ready — {len(pkg_bytes)//1024} KB")

        st.download_button(
            label=f"⬇️ Download {fname}",
            data=pkg_bytes,
            file_name=fname,
            mime="application/zip",
            use_container_width=True,
        )

        # Show contents
        with st.expander("Package contents"):
            with zipfile.ZipFile(io.BytesIO(pkg_bytes)) as zf:
                for info in sorted(zf.infolist(), key=lambda x: x.filename):
                    size_kb = info.file_size / 1024
                    st.write(f"  {info.filename}  ({size_kb:.1f} KB)")

    # ── Contents reference ─────────────────────────────────────────────────────
    with st.expander("What's in the package"):
        st.markdown("""
| File | Contents |
|------|----------|
| `00_Cover_Page.txt` | Device info, author, purpose, ANSI standard |
| `01_CEM_Design_Report.pdf` | Full physics-derived geometry report |
| `02_ANSI_Compliance_Summary.txt` | All ANSI checks with pass/fail vs limits |
| `03_Drop_Test_Results/` | All physical drop test JSONs + summary table |
| `04_Static_Load_Results/` | Static pawl/housing safety factor report |
| `05_State_Machine_Validation.txt` | State transitions verified against ANSI |
| `06_Constants_Sync_Report.txt` | Firmware vs Python model constants diff |
| `07_Design_History.json` | Every CEM run with timestamped dimensions |
| `08_HIL_Test_Report.json` | Hardware-in-the-loop test results |
| `09_Open_Items.txt` | Outstanding items before certification + assumptions |
        """)
