"""
Blender headless lattice generation pipeline.
All lattice geometry is generated by Blender running
in background mode via subprocess.
Supports: arc_weave, honeycomb, octet_truss
Forms: volumetric, skin_core
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Optional

from aria_os.lattice.params import LatticeParams, LatticeResult
from aria_os.lattice.validator import validate_params, estimate_weight


BLENDER_PATHS = [
    "blender",  # if in PATH
    # Windows 5.x (new installs)
    r"C:\Program Files\Blender Foundation\Blender 5.2\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 5.1\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 5.0\blender.exe",
    # Windows 4.x / LTS
    r"C:\Program Files\Blender Foundation\Blender 4.3\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 4.2\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 4.1\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 4.0\blender.exe",
    r"C:\Program Files\Blender Foundation\Blender 3.6\blender.exe",
    # Unix-like fallbacks
    "/usr/bin/blender",
    "/Applications/Blender.app/Contents/MacOS/Blender",
]


def find_blender() -> Optional[str]:
    """Find Blender executable on this system."""
    for path in BLENDER_PATHS:
        try:
            result = subprocess.run(
                [path, "--version"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode == 0:
                version_line = result.stdout.split("\n")[0]
                print(f"[BLENDER] Found: {version_line} at {path}")
                return path
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
            continue
    return None


def run_blender_script(
    blender_exe: str,
    script_path: str,
    params_path: str,
    timeout: int = 300,
) -> dict:
    """
    Run a Blender Python script in background mode.
    Returns dict with success, stdout, stderr, output_files.
    """
    cmd = [
        blender_exe,
        "--background",
        "--factory-startup",
        "--python",
        script_path,
        "--",
        params_path,
    ]

    print(f"[BLENDER] Running: {' '.join(cmd[:4])} ...")

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
        )

        success = result.returncode == 0

        stdout = result.stdout or ""
        stderr = result.stderr or ""

        # Detect script-level errors signaled by the Blender script itself
        if "SCRIPT_ERROR" in stdout:
            for line in stdout.split("\n"):
                if "SCRIPT_ERROR" in line:
                    raise RuntimeError(f"Blender script error: {line}")

        if not success:
            print(f"[BLENDER] Failed (exit {result.returncode})")
            stderr_tail = stderr[-1000:] if stderr else ""
            if stderr_tail:
                print(f"[BLENDER] stderr: {stderr_tail}")
        else:
            print("[BLENDER] Completed successfully")

        return {
            "success": success,
            "stdout": stdout,
            "stderr": stderr,
            "returncode": result.returncode,
        }

    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "stdout": "",
            "stderr": f"Blender timed out after {timeout}s",
            "returncode": -1,
        }


def generate_lattice(params: LatticeParams) -> LatticeResult:
    """
    Main entry point. Routes to correct Blender script
    based on pattern type.
    """
    blender = find_blender()
    if blender is None:
        raise RuntimeError(
            "Blender not found. See outputs/INSTALL_BLENDER.md\n"
            "Install from: https://www.blender.org/download/"
        )

    warnings = validate_params(params)

    out_dir = Path("outputs") / "cad"
    step_path = str(out_dir / "step" / f"{params.part_name}.step")
    stl_path = str(out_dir / "stl" / f"{params.part_name}.stl")

    Path(step_path).parent.mkdir(parents=True, exist_ok=True)
    Path(stl_path).parent.mkdir(parents=True, exist_ok=True)

    params.step_path = step_path
    params.stl_path = stl_path

    params_file = Path("outputs") / "blender_params_temp.json"
    params_dict = {
        "pattern": params.pattern,
        "form": params.form,
        "width": params.width_mm,
        "height": params.height_mm,
        "depth": params.depth_mm,
        "cell_size": params.cell_size_mm,
        "strut_diameter": params.strut_diameter_mm,
        "skin_thickness": params.skin_thickness_mm,
        "frame_thickness": params.frame_thickness_mm,
        "interlaced": params.interlaced,
        "weave_offset_mm": params.weave_offset_mm,
        "process": params.process,
        "part_name": params.part_name,
        "output_stl": stl_path,
        "output_step": step_path,
    }
    params_file.parent.mkdir(parents=True, exist_ok=True)
    params_file.write_text(json.dumps(params_dict, indent=2), encoding="utf-8")

    scripts_dir = Path("aria_os") / "lattice" / "blender_scripts"
    script_map = {
        "arc_weave": scripts_dir / "arc_weave.py",
        "honeycomb": scripts_dir / "honeycomb.py",
        "octet_truss": scripts_dir / "octet_truss.py",
    }

    script = script_map.get(params.pattern)
    if script is None or not script.exists():
        raise RuntimeError(f"No Blender script for pattern: {params.pattern}")

    result = run_blender_script(blender, str(script), str(params_file))

    if not result["success"]:
        stderr_tail = result["stderr"][-500:] if result.get("stderr") else ""
        raise RuntimeError(f"Blender generation failed:\n{stderr_tail}")

    if not Path(stl_path).exists():
        raise RuntimeError(f"Blender ran but STL not found at {stl_path}")

    bbox = {"x": params.width_mm, "y": params.height_mm, "z": params.depth_mm}

    try:
        from stl import mesh as stl_mesh  # type: ignore
        import numpy as np  # type: ignore

        m = stl_mesh.Mesh.from_file(stl_path)
        bb = m.max_ - m.min_
        bbox = {
            "x": round(float(bb[0]), 2),
            "y": round(float(bb[1]), 2),
            "z": round(float(bb[2]), 2),
        }
    except Exception:
        pass

    meta_path = out_dir / "meta" / f"{params.part_name}.json"
    meta_path.parent.mkdir(parents=True, exist_ok=True)
    meta = {
        "part_name": params.part_name,
        "bbox_mm": bbox,
        "dims_mm": {
            "WIDTH_MM": params.width_mm,
            "HEIGHT_MM": params.height_mm,
            "DEPTH_MM": params.depth_mm,
            "CELL_SIZE_MM": params.cell_size_mm,
            "STRUT_DIAMETER_MM": params.strut_diameter_mm,
        },
        "lattice": {
            "pattern": params.pattern,
            "form": params.form,
            "interlaced": params.interlaced,
            "weave_offset_mm": params.weave_offset_mm,
            "generator": "blender_headless",
        },
    }
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    weight = estimate_weight(params, 0.25)
    passed = not any("will not print" in w for w in warnings)

    summary = (
        f"{params.pattern} {params.form}: "
        f"{bbox['x']:.0f}x{bbox['y']:.0f}x{bbox['z']:.0f}mm, "
        f"strut={params.strut_diameter_mm}mm, "
        f"cell={params.cell_size_mm}mm"
    )

    return LatticeResult(
        params=params,
        step_path=step_path,
        stl_path=stl_path,
        bbox_mm=bbox,
        cell_count=0,
        strut_count=0,
        min_feature_mm=params.strut_diameter_mm,
        estimated_weight_g=weight,
        process_warnings=warnings,
        passed_process_check=passed,
        summary=summary,
    )

