"""
ecad_simulator.py — DC operating-point + power-on transient SPICE simulation.

Generates a SPICE netlist from a component list and attempts simulation via
PySpice/ngspice.  When PySpice is unavailable the module falls back to an
algebraic DC analysis that catches the most common electrical problems without
requiring any external simulator.

Usage:
    from aria_os.ecad_simulator import simulate
    result = simulate(board_desc, components)
"""
from __future__ import annotations

import re
from typing import Any


# ─── Voltage rail constants ───────────────────────────────────────────────────

_RAIL_VOLTAGES: dict[str, float] = {
    "VCC_12V": 12.0,
    "12V":     12.0,
    "VCC_5V":  5.0,
    "5V":      5.0,
    "VCC_3V3": 3.3,
    "3V3":     3.3,
    "VCC":     3.3,  # default logic rail
    "GND":     0.0,
}

# MCU model: approximate current draw in amps at steady state
_MCU_CURRENT_MA: dict[str, float] = {
    "esp32":   250.0,   # ESP32 active WiFi/BLE peak (mA)
    "stm32":   100.0,   # STM32F4 at 168 MHz (mA)
    "arduino":  50.0,   # Arduino Nano (mA)
    "hx711":     1.5,
    "mpu":      10.0,
    "ams1117":   5.0,   # LDO quiescent
    "tp4056":    1.0,
    "ss49e":     5.0,   # Hall sensor
}

# GPIO current limit per IEC/GPIO specs
_GPIO_MAX_MA = 20.0

# Minimum pull-up resistor on a 3.3 V rail before the GPIO source limit is exceeded
_MIN_PULLUP_OHM_3V3 = 1000.0


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _component_list(components: list[Any]) -> list[dict]:
    """
    Normalise a mixed list of component dicts / dataclass instances to plain dicts.
    """
    out: list[dict] = []
    for c in (components or []):
        if isinstance(c, dict):
            out.append(c)
        else:
            out.append({
                "ref":         getattr(c, "ref",         ""),
                "value":       getattr(c, "value",       ""),
                "description": getattr(c, "description", ""),
                "x_mm":        getattr(c, "x_mm",        0.0),
                "y_mm":        getattr(c, "y_mm",        0.0),
            })
    return out


def _lower(c: dict, key: str) -> str:
    return str(c.get(key, "")).lower()


# ─── Netlist generation ───────────────────────────────────────────────────────

def generate_netlist(components: list[Any], nets: dict[str, Any]) -> str:
    """
    Generate a SPICE netlist string from the component list and net assignments.

    Modelled elements
    -----------------
    * Voltage sources  — one per distinct supply rail (VCC_3V3, VCC_5V, VCC_12V).
    * Resistors        — R_xxx components become SPICE R elements.
    * Capacitors       — C_xxx components become SPICE C elements.
    * MCUs / ICs       — modelled as constant-current loads to GND.
    * LEDs             — modelled as a 2 V forward-voltage source + series R.

    Parameters
    ----------
    components : list
        Component dicts or dataclass instances.
    nets : dict
        Optional net→node mapping.  Pass {} if no explicit net assignments exist;
        the generator will infer rail membership from component descriptions.

    Returns
    -------
    str
        Complete SPICE netlist (deck) as a single string.
    """
    comps = _component_list(components)
    lines: list[str] = [
        "* ARIA auto-generated SPICE netlist",
        "* Generated by aria_os/ecad_simulator.py",
        "",
    ]

    # Voltage sources for known rails
    rails_emitted: set[str] = set()
    for rail, voltage in _RAIL_VOLTAGES.items():
        if rail == "GND":
            continue
        # Emit a source if any component is associated with this rail voltage
        needs_rail = any(
            str(voltage) in _lower(c, "description") or
            str(voltage) in _lower(c, "value") or
            rail.lower() in _lower(c, "description") or
            rail.lower() in _lower(c, "value")
            for c in comps
        )
        if needs_rail and rail not in rails_emitted:
            node = rail.replace("VCC_", "N_").replace("VCC", "N_VCC")
            lines.append(f"V{rail} {node} GND DC {voltage}")
            rails_emitted.add(rail)

    # Always emit a 3.3 V rail if any MCU present
    if any(_lower(c, "value") in ("esp32", "stm32") or
           any(kw in _lower(c, "value") for kw in ("esp32", "stm32", "arduino"))
           for c in comps) and "VCC_3V3" not in rails_emitted:
        lines.append("VVCC_3V3 N_VCC_3V3 GND DC 3.3")
        rails_emitted.add("VCC_3V3")

    lines.append("")

    r_count = 0
    c_count = 0
    i_count = 0

    for comp in comps:
        ref   = str(comp.get("ref",   "X"))
        value = str(comp.get("value", ""))
        desc  = str(comp.get("description", ""))
        val_l = value.lower()
        desc_l = desc.lower()

        # ── Resistors ──────────────────────────────────────────────────────────
        if ref.startswith("R"):
            r_count += 1
            ohm_match = re.search(r"(\d+(?:\.\d+)?)\s*[kK]", value)
            if ohm_match:
                ohm_val = float(ohm_match.group(1)) * 1000
            else:
                ohm_match2 = re.search(r"(\d+(?:\.\d+)?)\s*[rRoO]?", value)
                ohm_val = float(ohm_match2.group(1)) if ohm_match2 else 330.0
            node_p = "N_VCC_3V3" if "3v3" in desc_l or "3.3" in desc_l else "N_VCC"
            lines.append(f"R{r_count}_{ref} {node_p} N_R{r_count} {ohm_val:.1f}")

        # ── Capacitors ─────────────────────────────────────────────────────────
        elif ref.startswith("C"):
            c_count += 1
            if "10uf" in val_l or "10 uf" in val_l or "10µf" in val_l:
                cap_val = "10u"
            elif "100nf" in val_l or "100 nf" in val_l or "0.1uf" in val_l:
                cap_val = "100n"
            else:
                cap_val = "100n"
            node_p = "N_VCC_3V3"
            lines.append(f"C{c_count}_{ref} {node_p} GND {cap_val} IC=0")

        # ── MCU / IC current loads ─────────────────────────────────────────────
        elif ref.startswith("U") or ref.startswith("IC"):
            for kw, ma in _MCU_CURRENT_MA.items():
                if kw in val_l or kw in desc_l:
                    i_count += 1
                    rail_node = "N_VCC_3V3"
                    lines.append(f"I{i_count}_{ref} {rail_node} GND DC {ma/1000:.6f}")
                    break

        # ── LEDs: Vf=2V + series R ─────────────────────────────────────────────
        elif ref.startswith("D"):
            r_count += 1
            lines.append(f"VD_{ref}_vf N_LED_{ref}_a GND DC 2.0")
            lines.append(f"RD_{ref}_series N_VCC_3V3 N_LED_{ref}_a 330")

    lines += ["", ".OP", ".END", ""]
    return "\n".join(lines)


# ─── DC check (algebraic fallback) ───────────────────────────────────────────

def run_dc_check(netlist: str) -> dict:
    """
    DC operating-point check.

    Tries to import PySpice and run ngspice.  If PySpice is unavailable or
    ngspice is not installed, falls back to algebraic analysis of the netlist
    string.

    Algebraic checks performed
    --------------------------
    * Each voltage rail: verify a source (Vxxx) line exists.
    * Each resistor to GND: compute I = V/R; flag if > 20 mA (GPIO limit).
    * Pull-up resistors: flag if R < 1 kΩ on 3.3 V rail (exceeds GPIO source).

    Returns
    -------
    dict with keys:
        passed            : bool
        rail_voltages     : dict[str, float]   — detected rail → voltage
        current_violations : list[str]
        warnings           : list[str]
    """
    rail_voltages: dict[str, float] = {}
    current_violations: list[str] = []
    warnings_out: list[str] = []

    # ── Attempt PySpice / ngspice ──────────────────────────────────────────────
    try:
        from PySpice.Spice.Netlist import Circuit   # type: ignore
        from PySpice.Spice.NgSpice.Shared import NgSpiceShared  # type: ignore
        # If import succeeds but ngspice binary is missing this will raise OSError
        _ = NgSpiceShared.new_instance()
        warnings_out.append("DC: PySpice available but ngspice binary check skipped in headless mode")
    except ImportError:
        pass  # Normal path — fall through to algebraic analysis
    except Exception as exc:
        warnings_out.append(f"DC: PySpice/ngspice unavailable ({exc!r}), using algebraic fallback")

    # ── Algebraic analysis ─────────────────────────────────────────────────────
    for line in netlist.splitlines():
        line = line.strip()
        if not line or line.startswith("*") or line.startswith("."):
            continue

        tokens = line.split()
        if not tokens:
            continue

        element = tokens[0].upper()

        # Voltage sources: Vxxx node+ node- DC value
        if element.startswith("V") and len(tokens) >= 5 and tokens[3].upper() == "DC":
            try:
                v = float(tokens[4])
                rail_voltages[element] = v
            except ValueError:
                pass

        # Resistors: Rxxx node+ node- value
        elif element.startswith("R") and len(tokens) >= 4:
            node_p = tokens[1].upper()
            node_n = tokens[2].upper()
            try:
                r_val = float(tokens[3])
            except ValueError:
                continue
            if r_val <= 0:
                continue

            # Find voltage on positive node from the rail map
            rail_v: float | None = None
            for vname, vval in rail_voltages.items():
                # Match by rail node naming convention (N_VCC_3V3 → 3.3 V etc.)
                if "3V3" in node_p or "3.3" in node_p:
                    rail_v = 3.3
                    break
                elif "5V" in node_p:
                    rail_v = 5.0
                    break
                elif "12V" in node_p:
                    rail_v = 12.0
                    break
                elif "VCC" in node_p:
                    rail_v = 3.3  # default
                    break

            if rail_v is None:
                # Try to infer from the voltage source table
                for vname, vval in rail_voltages.items():
                    rail_v = vval
                    break

            if rail_v is not None and node_n in ("GND", "0"):
                i_ma = (rail_v / r_val) * 1000.0
                if i_ma > _GPIO_MAX_MA:
                    current_violations.append(
                        f"DC: {tokens[0]} — I={i_ma:.1f} mA exceeds GPIO limit "
                        f"(V={rail_v:.1f} V, R={r_val:.0f} Ω)"
                    )
                # Pull-up check (resistor between rail and signal node, not GND)
            elif rail_v is not None and "GND" not in node_n and node_n != "0":
                if rail_v <= 3.3 and r_val < _MIN_PULLUP_OHM_3V3:
                    warnings_out.append(
                        f"DC: {tokens[0]} — pull-up R={r_val:.0f} Ω on 3.3 V rail "
                        f"may exceed GPIO source current"
                    )

    # Verify at least one rail was found
    if not rail_voltages:
        warnings_out.append("DC: no voltage source elements found in netlist")

    passed = len(current_violations) == 0
    return {
        "passed":             passed,
        "rail_voltages":      rail_voltages,
        "current_violations": current_violations,
        "warnings":           warnings_out,
    }


# ─── Power-on sequencing check ────────────────────────────────────────────────

def run_power_on_check(components: list[Any]) -> dict:
    """
    Check power-on sequencing rules for known ARIA board components.

    Rules checked
    -------------
    * ESP32  — 3.3 V must be stable before GPIO outputs are enabled.
              Modelled as: a 100 nF decoupling cap must exist in BOM.
    * STM32  — same rule as ESP32.
    * VESC   — 12 V motor rail must be present before 3.3 V logic rail.
              Modelled as: barrel jack must exist when VESC is present.

    Returns
    -------
    dict with keys:
        passed      : bool
        sequence_ok : bool
        warnings    : list[str]
    """
    comps = _component_list(components)
    warnings_out: list[str] = []
    sequence_ok = True

    val_set  = {_lower(c, "value")       for c in comps}
    desc_set = {_lower(c, "description") for c in comps}

    has_esp32   = any("esp32"   in v for v in val_set | desc_set)
    has_stm32   = any("stm32"   in v for v in val_set | desc_set)
    has_vesc    = any("vesc"    in v or "motor" in v for v in val_set | desc_set)
    has_100nf   = any("100nf"   in v or "100 nf" in v for v in val_set)
    has_barrel  = any("barrel"  in v for v in val_set | desc_set)
    has_ldo_3v3 = any("ams1117" in v or "ldo"    in v for v in val_set | desc_set)

    # ESP32 / STM32: require decoupling cap as proxy for stable 3.3 V before boot
    if has_esp32 and not has_100nf:
        warnings_out.append(
            "Power-on: ESP32 present but no 100 nF decoupling cap — 3.3 V rail may "
            "not be stable before GPIO outputs activate"
        )
        sequence_ok = False

    if has_stm32 and not has_100nf:
        warnings_out.append(
            "Power-on: STM32 present but no 100 nF decoupling cap — 3.3 V rail may "
            "not be stable before GPIO outputs activate"
        )
        sequence_ok = False

    # VESC: 12 V rail must be supplied before 3.3 V logic
    if has_vesc and not has_barrel:
        warnings_out.append(
            "Power-on: VESC/motor driver present but no 12 V barrel jack — "
            "12 V motor rail cannot be verified to come up before 3.3 V logic"
        )
        sequence_ok = False

    if has_vesc and has_barrel and not has_ldo_3v3:
        warnings_out.append(
            "Power-on: VESC + barrel jack present but no LDO found — "
            "3.3 V logic rail may float during VESC power-on"
        )

    passed = sequence_ok
    return {
        "passed":      passed,
        "sequence_ok": sequence_ok,
        "warnings":    warnings_out,
    }


# ─── Main entry point ─────────────────────────────────────────────────────────

def simulate(board_desc: str, components: list[Any]) -> dict:
    """
    Full simulation pipeline: netlist generation → DC check → power-on check.

    Parameters
    ----------
    board_desc : str
        Natural-language board description (used for context only).
    components : list
        Parsed component list (dicts or dataclass instances).

    Returns
    -------
    dict with keys:
        passed       : bool
        netlist      : str    — generated SPICE netlist
        dc           : dict   — run_dc_check result
        power_on     : dict   — run_power_on_check result
        warnings     : list[str]
    """
    if not components:
        print("[SPICE] DC: PASS (no components)")
        print("[SPICE] Power-on: PASS (no components)")
        return {
            "passed":   True,
            "netlist":  "",
            "dc":       {"passed": True, "rail_voltages": {}, "current_violations": [], "warnings": []},
            "power_on": {"passed": True, "sequence_ok": True, "warnings": []},
            "warnings": ["simulate: no components — skipped"],
        }

    netlist    = generate_netlist(components, nets={})
    dc_result  = run_dc_check(netlist)
    pon_result = run_power_on_check(components)

    dc_status  = "PASS" if dc_result["passed"]  else f"FAIL ({len(dc_result['current_violations'])} violation(s))"
    pon_status = "PASS" if pon_result["passed"] else f"FAIL ({len(pon_result['warnings'])} warning(s))"

    print(f"[SPICE] DC: {dc_status}")
    print(f"[SPICE] Power-on: {pon_status}")

    all_warnings = list(dc_result.get("warnings", [])) + list(pon_result.get("warnings", []))
    passed = dc_result["passed"] and pon_result["passed"]

    return {
        "passed":   passed,
        "netlist":  netlist,
        "dc":       dc_result,
        "power_on": pon_result,
        "warnings": all_warnings,
    }
