# -*- coding: utf-8 -*-
"""
ecad_reviewer.py - ECAD layout and component reviewer for KiCad pcbnew scripts.

Analyzes an existing *_pcbnew.py script (generated by ecad_generator.py), suggests
layout/component improvements via LLM (or heuristic fallback), applies selected edits,
and writes a revised script alongside the original.

Usage:
    from aria_os.ecad.ecad_reviewer import review_ecad
    out = review_ecad("outputs/ecad/aria_esp32_board/aria_esp32_board_pcbnew.py")

    # With hint and non-interactive (apply all suggestions automatically):
    out = review_ecad(script_path, hint="add I2C header", interactive=False)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

# LLM client (graceful import)
try:
    from aria_os.llm_client import call_llm  # type: ignore
    _HAS_LLM = True
except ImportError:
    _HAS_LLM = False

    def call_llm(prompt: str, system: str, *, repo_root=None) -> "str | None":  # type: ignore
        return None


# =============================================================================
# Step 1 - Analysis
# =============================================================================

def _analyse_script(script_text: str, bom: "dict | None") -> dict:
    """
    Parse a pcbnew Python script (and optional BOM dict) to extract a structured
    analysis dictionary.  Pure regex -- the script is never executed.
    """
    analysis: dict[str, Any] = {
        "board_dims": None,
        "components": [],
        "component_count": 0,
        "has_esp32": False,
        "has_stm32": False,
        "has_power_connector": False,
        "has_uart": False,
        "has_i2c": False,
        "has_spi": False,
        "has_usb": False,
        "decoupling_caps_count": 0,
        "has_fuse": False,
        "has_tvs": False,
        "firmware_pins": [],
    }

    # Board dimensions: BOARD_W_MM = 80.0 / BOARD_H_MM = 60.0
    w_m = re.search(r"BOARD_W_MM\s*=\s*([\d.]+)", script_text)
    h_m = re.search(r"BOARD_H_MM\s*=\s*([\d.]+)", script_text)
    if w_m and h_m:
        analysis["board_dims"] = f"{w_m.group(1)}x{h_m.group(1)}mm"
    else:
        # Fallback: SetBoardSize or mm(80), mm(60) patterns
        bsize = re.search(r"SetBoardSize.*?mm\((\d+)\).*?mm\((\d+)\)", script_text)
        if bsize:
            analysis["board_dims"] = f"{bsize.group(1)}x{bsize.group(2)}mm"

    # Component refs from add_fp calls:  add_fp(board, "U1", "ESP32-S3-WROOM-1", ...)
    refs: list[str] = re.findall(r'add_fp\s*\([^,]+,\s*"([A-Z]+\d+)"', script_text)
    # Also catch direct footprint adds: fp.SetReference("C3")
    refs += re.findall(r'SetReference\s*\(\s*"([A-Z]+\d+)"\s*\)', script_text)
    # Deduplicate preserving order
    seen: set[str] = set()
    unique_refs: list[str] = []
    for r in refs:
        if r not in seen:
            seen.add(r)
            unique_refs.append(r)

    # Supplement with BOM if present
    if bom and "components" in bom:
        for comp in bom["components"]:
            r = comp.get("ref", "")
            if r and r not in seen:
                seen.add(r)
                unique_refs.append(r)

    analysis["components"] = unique_refs
    analysis["component_count"] = len(unique_refs)

    # MCU detection
    lower = script_text.lower()
    analysis["has_esp32"] = bool(re.search(r"esp32", lower))
    analysis["has_stm32"] = bool(re.search(r"stm32", lower))

    # Interface detection
    analysis["has_power_connector"] = bool(
        re.search(r"barrel.?jack|vin|12v|24v|power.?connector", lower)
    )
    analysis["has_uart"] = bool(re.search(r"uart|tx.*rx|serial", lower))
    analysis["has_i2c"] = bool(re.search(r"i2c|sda|scl", lower))
    analysis["has_spi"] = bool(re.search(r"\bspi\b|mosi|miso|sclk", lower))
    analysis["has_usb"] = bool(re.search(r"\busb\b|usb.?c|micro.?usb", lower))

    # Decoupling capacitors -- count unique C* refs; use BOM qty when available
    cap_refs = {r for r in unique_refs if r.startswith("C")}
    if bom and "components" in bom:
        total_caps = 0
        for comp in bom["components"]:
            if comp.get("ref", "").startswith("C"):
                total_caps += comp.get("qty", 1)
        analysis["decoupling_caps_count"] = total_caps
    else:
        analysis["decoupling_caps_count"] = len(cap_refs)

    # Protection components
    fuse_refs = {r for r in unique_refs if r.startswith("F")}
    analysis["has_fuse"] = (
        bool(fuse_refs) or bool(re.search(r"fuse|polyfuse|resettable", lower))
    )

    tvs_in_names = bool(
        re.search(r"\btvs\b|transient.?voltage", lower)
    )
    tvs_d_refs = {
        r for r in unique_refs
        if r.startswith("D") and re.search(r"tvs|smaj|smbj|protection", lower)
    }
    analysis["has_tvs"] = bool(tvs_d_refs) or tvs_in_names

    # Firmware pins: lines like  # PIN_BRAKE = PB13
    fw_pins = re.findall(r"#\s*(PIN_\w+|\w+_GPIO_NUM)\s*=\s*(\S+)", script_text)
    analysis["firmware_pins"] = [f"{k}={v}" for k, v in fw_pins]

    return analysis


def _analyse_bom_file(bom_path: Path) -> "dict | None":
    """Load BOM JSON if present; return None on any error."""
    if not bom_path.exists():
        return None
    try:
        return json.loads(bom_path.read_text(encoding="utf-8"))
    except Exception:
        return None


# =============================================================================
# Step 2 - Suggestion generation (LLM or heuristic)
# =============================================================================

_SYSTEM_PROMPT = (
    "You are an experienced PCB designer and embedded systems engineer reviewing a "
    "KiCad board layout script.  Provide specific, actionable suggestions as a JSON array."
)


def _build_llm_prompt(analysis: dict, hint: str, script_lines: list[str]) -> str:
    preview = "\n".join(script_lines[:100])
    schema_example = (
        '[\n'
        '  {\n'
        '    "id": <int>,\n'
        '    "description": "<specific, actionable description>",\n'
        '    "priority": "required" | "recommended" | "optional",\n'
        '    "edit_type": "add_component" | "set_trace_width" | "add_comment"'
        ' | "add_net_tie" | "rename_ref" | "add_keepout",\n'
        '    "component": {"ref": "...", "value": "...", "footprint": "...", "description": "..."},\n'
        '    "position_hint": "...",\n'
        '    "net": "...",\n'
        '    "width_mm": <float>\n'
        '  }\n'
        ']'
    )
    return (
        "Review the following KiCad pcbnew script and return ONLY a JSON array of improvement "
        "suggestions.  Each suggestion must follow this exact schema:\n"
        + schema_example + "\n\n"
        + f"Board analysis:\n{json.dumps(analysis, indent=2)}\n\n"
        + (f"User hint: {hint}\n\n" if hint else "")
        + f"First 100 lines of script:\n```python\n{preview}\n```\n\n"
        + "Return ONLY the JSON array -- no other text."
    )


def _heuristic_suggestions(analysis: dict) -> list[dict]:
    """
    Generate basic suggestions from the analysis dict when no LLM is available.
    """
    suggestions: list[dict] = []
    sid = 1

    # Decoupling caps: ESP32 needs >=4, STM32 needs >=6
    min_caps = 0
    if analysis["has_esp32"]:
        min_caps += 4
    if analysis["has_stm32"]:
        min_caps += 6
    found_caps = analysis["decoupling_caps_count"]
    if min_caps > 0 and found_caps < min_caps:
        missing = min_caps - found_caps
        who = []
        if analysis["has_esp32"]:
            who.append("ESP32")
        if analysis["has_stm32"]:
            who.append("STM32")
        who_str = "/".join(who)
        suggestions.append({
            "id": sid,
            "description": (
                f"Add {missing} more 100nF decoupling capacitor(s) for {who_str} "
                f"power pins -- only {found_caps} found, need {min_caps} minimum"
            ),
            "priority": "required",
            "edit_type": "add_component",
            "component": {
                "ref": f"C{found_caps + 1}",
                "value": "100nF",
                "footprint": "Capacitor_SMD:C_0402_1005Metric",
                "description": "Decoupling cap VDD",
            },
            "position_hint": f"Place near {who_str} VDD pins, within 0.5mm",
        })
        sid += 1

    # Fuse on power input
    if analysis["has_power_connector"] and not analysis["has_fuse"]:
        suggestions.append({
            "id": sid,
            "description": (
                "Add 500mA polyfuse on VIN before LDO -- no overcurrent protection found"
            ),
            "priority": "required",
            "edit_type": "add_component",
            "component": {
                "ref": "F1",
                "value": "500mA polyfuse",
                "footprint": "Fuse:Fuse_1812_4532Metric",
                "description": "Overcurrent protection on VIN",
            },
            "position_hint": "Place on VIN net before LDO input",
        })
        sid += 1

    # TVS on power input
    if analysis["has_power_connector"] and not analysis["has_tvs"]:
        suggestions.append({
            "id": sid,
            "description": (
                "Add TVS diode on VIN for ESD/transient protection -- "
                "recommended for external power connections"
            ),
            "priority": "recommended",
            "edit_type": "add_component",
            "component": {
                "ref": "D2",
                "value": "SMAJ15A",
                "footprint": "Diode_SMD:D_SMA",
                "description": "TVS diode 15V clamping on VIN",
            },
            "position_hint": "Place between power connector and fuse on VIN",
        })
        sid += 1

    # I2C header missing but ESP32 present
    if analysis["has_esp32"] and not analysis["has_i2c"]:
        suggestions.append({
            "id": sid,
            "description": (
                "Add I2C header (SDA/SCL/3V3/GND) -- ESP32 has I2C capability "
                "but no I2C connector was found in the script"
            ),
            "priority": "recommended",
            "edit_type": "add_component",
            "component": {
                "ref": "J5",
                "value": "JST-XH-4P-I2C",
                "footprint": "Connector_JST:JST_XH_B4B-XH-A_1x04_P2.50mm_Vertical",
                "description": "I2C expansion header (SDA/SCL/3V3/GND)",
            },
            "position_hint": "Place on board edge for easy access",
        })
        sid += 1

    # VIN trace width reminder when power connector present
    if analysis["has_power_connector"]:
        suggestions.append({
            "id": sid,
            "description": (
                "Verify VIN trace width -- for 12V/500mA+ input, trace must be >=1.0mm. "
                "Default 0.25mm traces will violate IPC-2221 thermal limits."
            ),
            "priority": "recommended",
            "edit_type": "set_trace_width",
            "net": "VIN",
            "width_mm": 1.0,
        })
        sid += 1

    return suggestions


def _call_llm_suggestions(
    analysis: dict,
    hint: str,
    script_lines: list[str],
    repo_root: "Path | None",
) -> "list[dict] | None":
    """
    Call LLM and parse JSON array from response.
    Returns None if LLM is unavailable or returns unparseable output.
    """
    if not _HAS_LLM:
        return None
    prompt = _build_llm_prompt(analysis, hint, script_lines)
    raw = call_llm(prompt, _SYSTEM_PROMPT, repo_root=repo_root)
    if not raw:
        return None
    # Extract JSON array from response (LLM may wrap in prose)
    m = re.search(r"\[.*\]", raw, re.DOTALL)
    if not m:
        return None
    try:
        parsed = json.loads(m.group(0))
        if isinstance(parsed, list):
            return parsed
    except json.JSONDecodeError:
        pass
    return None


# =============================================================================
# Step 3 - Interactive prompt
# =============================================================================

_PRIORITY_LABEL = {
    "required": "REQUIRED    ",
    "recommended": "RECOMMENDED ",
    "optional": "OPTIONAL    ",
}


def _display_suggestions(suggestions: list[dict], analysis: dict, file_name: str) -> None:
    dims = analysis.get("board_dims") or "unknown dims"
    parts: list[str] = []
    if analysis["has_esp32"]:
        parts.append("ESP32")
    if analysis["has_stm32"]:
        parts.append("STM32")
    board_desc = " + ".join(parts) if parts else "board"
    n_comp = analysis["component_count"]

    print(f"\n[ECAD REVIEW] {len(suggestions)} suggestion(s) for {file_name}:")
    print(f"  Board: {board_desc}, {dims}, {n_comp} components found")
    for s in suggestions:
        label = _PRIORITY_LABEL.get(s.get("priority", "optional"), "          ")
        print(f"  [{s['id']}] {label} {s['description']}")


def _prompt_selection(suggestions: list[dict], interactive: bool) -> list[dict]:
    """
    Ask user which suggestions to apply.  Returns filtered list.
    If interactive=False, apply all required + recommended automatically.
    """
    if not interactive:
        selected = [s for s in suggestions if s.get("priority") in ("required", "recommended")]
        if not selected:
            selected = suggestions
        return selected

    required = [s for s in suggestions if s.get("priority") == "required"]
    default_ids = {s["id"] for s in required} if required else {s["id"] for s in suggestions}
    default_label = "all required" if required else "all"

    print(
        f"\nApply which? [all / comma-separated ids e.g. 1,2,3 / none] "
        f"(default: {default_label}): ",
        end="",
        flush=True,
    )
    try:
        raw = sys.stdin.readline().strip()
    except (EOFError, OSError):
        raw = ""

    if not raw:
        return [s for s in suggestions if s["id"] in default_ids]
    if raw.lower() == "all":
        return suggestions
    if raw.lower() == "none":
        return []
    try:
        ids = {int(x.strip()) for x in raw.split(",") if x.strip()}
        return [s for s in suggestions if s["id"] in ids]
    except ValueError:
        print("[ECAD REVIEW] Invalid input -- applying default (all required).")
        return [s for s in suggestions if s["id"] in default_ids]


# =============================================================================
# Step 4 - Apply edits
# =============================================================================

def _find_last_component_position(script_text: str) -> "tuple[float, float]":
    """
    Scan existing add_fp calls to find the last x,y position used.
    Returns (x, y) in mm; defaults to (5.0, 45.0) if none found.
    """
    # Pattern: add_fp(board, "REF", "VALUE", "FOOTPRINT", x, y, ...)
    matches = re.findall(
        r'add_fp\s*\([^,]+,\s*"[^"]+",\s*"[^"]+",\s*"[^"]+",\s*([\d.]+),\s*([\d.]+)',
        script_text,
    )
    if matches:
        last = matches[-1]
        return float(last[0]), float(last[1])
    return 5.0, 45.0


def _apply_add_component(
    script_text: str,
    suggestion: dict,
    x: float,
    y: float,
) -> str:
    comp = suggestion.get("component", {})
    ref = comp.get("ref", "C99")
    value = comp.get("value", "unknown")
    footprint = comp.get("footprint", "")
    description = comp.get("description", suggestion.get("description", ""))
    position_hint = suggestion.get("position_hint", "")

    block = (
        f"\n# {description}\n"
        f"# Position hint: {position_hint}\n"
        f"add_fp(board, \"{ref}\", \"{value}\", \"{footprint}\","
        f" {x:.2f}, {y:.2f}, \"{description}\")\n"
    )

    # Insert before pcbnew.Refresh() / board.Save() if present, else append
    for marker in ("pcbnew.Refresh()", "board.Save("):
        idx = script_text.find(marker)
        if idx != -1:
            return script_text[:idx] + block + script_text[idx:]

    return script_text + block


def _apply_set_trace_width(script_text: str, suggestion: dict) -> str:
    net = suggestion.get("net", "VIN")
    width_mm = suggestion.get("width_mm", 1.0)

    block = (
        f"\n# Set trace width for net {net} to {width_mm}mm\n"
        f"for track in board.GetTracks():\n"
        f"    if track.GetNetname() == \"{net}\":\n"
        f"        track.SetWidth(pcbnew.FromMM({width_mm}))\n"
    )

    for marker in ("pcbnew.Refresh()", "board.Save("):
        idx = script_text.find(marker)
        if idx != -1:
            return script_text[:idx] + block + script_text[idx:]

    return script_text + block


def _apply_add_comment(script_text: str, suggestion: dict) -> str:
    description = suggestion.get("description", "")
    block = f"\n# REVIEW NOTE: {description}\n"
    return script_text + block


def _apply_add_keepout(script_text: str, suggestion: dict) -> str:
    description = suggestion.get("description", "")
    block = (
        f"\n# KEEPOUT: {description}\n"
        "# TODO: Add keepout zone manually in KiCad PCB editor (Place > Rule Area).\n"
    )
    return script_text + block


def _apply_suggestions(script_text: str, selected: list[dict]) -> "tuple[str, list[dict]]":
    """
    Apply a list of selected suggestions to the script text.
    Returns (revised_text, list_of_applied_suggestions).
    """
    revised = script_text
    applied: list[dict] = []

    # Start new component placements just after the last known component
    last_x, last_y = _find_last_component_position(script_text)
    stagger = 0

    for suggestion in selected:
        edit_type = suggestion.get("edit_type", "add_comment")
        try:
            if edit_type == "add_component":
                nx = last_x
                ny = last_y + 5.0 + stagger * 5.0
                stagger += 1
                revised = _apply_add_component(revised, suggestion, nx, ny)
                applied.append(suggestion)

            elif edit_type == "set_trace_width":
                revised = _apply_set_trace_width(revised, suggestion)
                applied.append(suggestion)

            elif edit_type == "add_comment":
                revised = _apply_add_comment(revised, suggestion)
                applied.append(suggestion)

            elif edit_type in ("add_net_tie", "rename_ref", "add_keepout"):
                revised = _apply_add_keepout(revised, suggestion)
                applied.append(suggestion)

            else:
                # Unknown edit type -- add as comment
                revised = _apply_add_comment(revised, suggestion)
                applied.append(suggestion)

        except Exception as exc:
            print(f"[ECAD REVIEW] Warning: could not apply edit {suggestion.get('id')}: {exc}")

    return revised, applied


# =============================================================================
# Step 5 - Save
# =============================================================================

def _write_review_sidecar(
    out_dir: Path,
    stem: str,
    analysis: dict,
    suggestions: list[dict],
    applied: list[dict],
) -> Path:
    sidecar = out_dir / f"{stem}_revised_review.json"
    data = {
        "analysis": analysis,
        "suggestions": suggestions,
        "applied": [s["id"] for s in applied],
        "applied_count": len(applied),
    }
    sidecar.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return sidecar


# =============================================================================
# Public API
# =============================================================================

def review_ecad(
    script_path: "str | Path",
    hint: str = "",
    repo_root: "Path | None" = None,
    interactive: bool = True,
) -> Path:
    """
    Analyze a KiCad pcbnew Python script, suggest improvements, apply selected
    edits, and write a revised script alongside the original.

    Parameters
    ----------
    script_path:
        Path to *_pcbnew.py (or *_bom.json -- will resolve to the .py sibling).
    hint:
        Optional user guidance, e.g. "add I2C header" or "increase trace width".
    repo_root:
        Repository root passed through to call_llm for key resolution.
    interactive:
        When True (default) prompt user to select suggestions.
        When False, apply all required + recommended automatically.

    Returns
    -------
    Path to the revised script (<stem>_revised.py in the same directory).
    """
    script_path = Path(script_path)

    # Allow passing a BOM JSON path -- resolve to .py sibling
    if script_path.suffix == ".json":
        py_path = script_path.parent / script_path.name.replace("_bom.json", "_pcbnew.py")
        script_path = py_path

    if not script_path.exists():
        raise FileNotFoundError(f"[ECAD REVIEW] Script not found: {script_path}")

    script_text = script_path.read_text(encoding="utf-8")
    script_lines = script_text.splitlines()

    # Derive BOM path
    bom_path = script_path.parent / script_path.name.replace("_pcbnew.py", "_bom.json")
    bom = _analyse_bom_file(bom_path)

    # Step 1: Analyse
    analysis = _analyse_script(script_text, bom)
    analysis["file"] = script_path.name

    # Step 2: Generate suggestions
    suggestions = _call_llm_suggestions(analysis, hint, script_lines, repo_root)
    if not suggestions:
        suggestions = _heuristic_suggestions(analysis)

    # Ensure IDs are sequential integers
    for i, s in enumerate(suggestions, start=1):
        s["id"] = i

    if not suggestions:
        print(f"[ECAD REVIEW] No suggestions generated for {script_path.name}.")
        # Always return a valid path
        out_path = script_path.parent / f"{script_path.stem}_revised.py"
        out_path.write_text(script_text, encoding="utf-8")
        return out_path

    # Step 3: Display and select
    _display_suggestions(suggestions, analysis, script_path.name)
    selected = _prompt_selection(suggestions, interactive)

    if not selected:
        print("[ECAD REVIEW] No edits selected -- writing unmodified revised script.")
        out_path = script_path.parent / f"{script_path.stem}_revised.py"
        out_path.write_text(script_text, encoding="utf-8")
        _write_review_sidecar(script_path.parent, script_path.stem, analysis, suggestions, [])
        return out_path

    # Step 4: Apply
    revised_text, applied = _apply_suggestions(script_text, selected)

    # Step 5: Save
    out_path = script_path.parent / f"{script_path.stem}_revised.py"
    out_path.write_text(revised_text, encoding="utf-8")

    _write_review_sidecar(
        script_path.parent, script_path.stem, analysis, suggestions, applied
    )

    # Friendly display path relative to cwd when possible
    try:
        display = out_path.relative_to(Path.cwd())
    except ValueError:
        display = out_path

    print(
        f"[ECAD REVIEW] Applied {len(applied)} edit(s). "
        f"Revised script: {display}"
    )
    print(
        "[ECAD REVIEW] Run revised script in KiCad scripting console to apply to your board."
    )

    return out_path


# =============================================================================
# CLI entry point
# =============================================================================

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Review and improve a KiCad pcbnew Python script."
    )
    parser.add_argument("script", help="Path to *_pcbnew.py or *_bom.json")
    parser.add_argument("--hint", default="", help="Optional guidance for the reviewer")
    parser.add_argument(
        "--no-interactive",
        action="store_true",
        help="Apply all required + recommended suggestions automatically",
    )
    args = parser.parse_args()

    result = review_ecad(
        args.script,
        hint=args.hint,
        interactive=not args.no_interactive,
    )
    print(f"Output: {result}")
