"""
Direct .kicad_pcb file writer — produces a fabricable KiCad PCB file from
a BOM JSON without requiring KiCad to be installed.

Why: ecad_generator.py has produced Python scripts you'd run inside KiCad's
pcbnew to materialize a board. That's awkward — the user wants the actual
.kicad_pcb file they can open in KiCad / send to a fab house. This module
emits the KiCad 7+ s-expression format directly.

Output format reference:
  https://dev-docs.kicad.org/en/file-formats/sexpr-pcb/

Limitations (vs hand-designed PCB):
  - Footprints are minimal placeholders (rectangle outline + pad grid).
    They're real KiCad footprints (you can move/rotate them), just not
    pulled from KiCad's libraries.
  - No traces yet — components are placed but not routed. Add traces
    manually in KiCad or via auto-router.
  - No silkscreen text beyond reference designators.

Usage:
  from aria_os.ecad.kicad_pcb_writer import write_kicad_pcb
  write_kicad_pcb(bom_path, out_pcb_path, board_name="my_board")
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any
from uuid import uuid4


# KiCad standard layer stack for a 2-layer board
_LAYERS_2L = """\
    (layers
        (0 "F.Cu" signal)
        (31 "B.Cu" signal)
        (32 "B.Adhes" user "B.Adhesive")
        (33 "F.Adhes" user "F.Adhesive")
        (34 "B.Paste" user)
        (35 "F.Paste" user)
        (36 "B.SilkS" user "B.Silkscreen")
        (37 "F.SilkS" user "F.Silkscreen")
        (38 "B.Mask" user)
        (39 "F.Mask" user)
        (40 "Dwgs.User" user "User.Drawings")
        (41 "Cmts.User" user "User.Comments")
        (42 "Eco1.User" user "User.Eco1")
        (43 "Eco2.User" user "User.Eco2")
        (44 "Edge.Cuts" user)
        (45 "Margin" user)
        (46 "B.CrtYd" user "B.Courtyard")
        (47 "F.CrtYd" user "F.Courtyard")
        (48 "B.Fab" user)
        (49 "F.Fab" user)
        (50 "User.1" user)
        (51 "User.2" user)
        (52 "User.3" user)
        (53 "User.4" user)
        (54 "User.5" user)
    )"""


def write_kicad_pcb(
    bom_path: str | Path,
    out_pcb_path: str | Path | None = None,
    *,
    board_name: str | None = None,
    pcb_thk_mm: float = 1.6,
) -> Path:
    """Write a real .kicad_pcb file (s-expression format) from a BOM JSON.

    Returns the path to the written .kicad_pcb file.
    """
    bom_path = Path(bom_path)
    bom = json.loads(bom_path.read_text(encoding="utf-8"))
    components = bom.get("components", []) or []
    board_w = float(bom.get("board_w_mm", 0)) or _infer_board(components, "w")
    board_h = float(bom.get("board_h_mm", 0)) or _infer_board(components, "h")
    name = board_name or bom.get("board_name") or bom_path.stem

    if out_pcb_path is None:
        out_pcb_path = bom_path.parent / f"{name}.kicad_pcb"
    out_pcb_path = Path(out_pcb_path)

    # KiCad places origin at the top-left of the page. Board coords in BOM
    # are 0-based at lower-left (math convention). We translate Y so that
    # KiCad-Y = page_offset_mm + (board_h - bom_y).
    page_x_mm = 100.0  # offset of board on the KiCad page
    page_y_mm = 100.0

    nets = _collect_nets(components)
    net_lines = "\n".join(
        f'    (net {i} "{n}")' for i, n in enumerate(nets)
    )

    footprint_blocks = []
    for c in components:
        ref = str(c.get("ref", "?"))
        value = str(c.get("value", ""))
        x = float(c.get("x_mm", 0))
        y = float(c.get("y_mm", 0))
        w = float(c.get("width_mm", 1))
        h = float(c.get("height_mm", 1))
        rotation = float(c.get("rotation_deg", 0))
        footprint_field = str(c.get("footprint", "Generic:Generic"))

        # Translate to KiCad page coords (Y inverted)
        kx = page_x_mm + x + w / 2.0
        ky = page_y_mm + (board_h - y) - h / 2.0

        footprint_blocks.append(
            _build_footprint_sexpr(ref, value, footprint_field,
                                   kx, ky, rotation, w, h))

    # Board outline rectangle on Edge.Cuts layer
    edge_cuts = _build_edge_cuts(page_x_mm, page_y_mm, board_w, board_h)

    # Final s-expression
    timestamp = int(time.time())
    pcb = f'''(kicad_pcb
    (version 20221018)
    (generator "aria_os.kicad_pcb_writer")
    (general
        (thickness {pcb_thk_mm:.2f})
    )
    (paper "A4")
    (title_block
        (title "{name}")
        (date "{time.strftime('%Y-%m-%d')}")
        (rev "1.0")
        (company "ARIA-OS")
        (comment 1 "Generated by aria_os/ecad/kicad_pcb_writer.py")
    )
{_LAYERS_2L}
    (setup
        (pad_to_mask_clearance 0.051)
        (solder_mask_min_width 0.25)
        (pcbplotparams
            (layerselection 0x00010fc_ffffffff)
            (disableapertmacros false)
            (usegerberextensions false)
            (usegerberattributes true)
            (usegerberadvancedattributes true)
            (creategerberjobfile true)
            (svguseinch false)
            (svgprecision 6)
            (excludeedgelayer true)
            (plotframeref false)
            (viasonmask false)
            (mode 1)
            (useauxorigin false)
            (hpglpennumber 1)
            (hpglpenspeed 20)
            (hpglpendiameter 15.000000)
            (dxfpolygonmode true)
            (dxfimperialunits true)
            (dxfusepcbnewfont true)
            (psnegative false)
            (psa4output false)
            (plotreference true)
            (plotvalue true)
            (plotinvisibletext false)
            (sketchpadsonfab false)
            (subtractmaskfromsilk false)
            (outputformat 1)
            (mirror false)
            (drillshape 1)
            (scaleselection 1)
            (outputdirectory "gerbers/")
        )
    )
    (net 0 "")
{net_lines}
{edge_cuts}
{chr(10).join(footprint_blocks)}
)
'''
    out_pcb_path.write_text(pcb, encoding="utf-8")
    return out_pcb_path


def _build_footprint_sexpr(ref: str, value: str, footprint_field: str,
                           kx: float, ky: float, rotation: float,
                           w: float, h: float) -> str:
    """Build a minimal but valid KiCad footprint s-expression.

    The actual graphical body is a rectangle on F.SilkS + F.Fab + F.CrtYd,
    sized to (w, h). Pads: a 2x2 grid of through-hole pads inside the body
    so the footprint is 'wirable' (not just visual).
    """
    fp_uuid = str(uuid4())
    # Decide number of pads based on size — bigger components get more pads.
    n_pads = max(2, min(8, int(w / 3.0)))
    pad_pitch_x = max(2.0, w / (n_pads + 1))
    pad_y = h * 0.3

    pad_lines = []
    for i in range(n_pads):
        px = -w / 2.0 + pad_pitch_x * (i + 1)
        for sign in (-1, 1):
            py = sign * pad_y
            pad_lines.append(
                f'        (pad "{i+1}" smd rect '
                f'(at {px:.3f} {py:.3f}) '
                f'(size 1.0 0.6) '
                f'(layers "F.Cu" "F.Paste" "F.Mask"))'
            )

    return f'''    (footprint "{footprint_field}"
        (layer "F.Cu")
        (tedit {int(time.time()):X})
        (tstamp {fp_uuid})
        (at {kx:.3f} {ky:.3f} {rotation:.1f})
        (descr "auto-generated by aria_os")
        (attr smd)
        (fp_text reference "{ref}" (at 0 {-h/2 - 1.0:.3f}) (layer "F.SilkS")
            (effects (font (size 0.8 0.8) (thickness 0.15)))
            (tstamp {uuid4()}))
        (fp_text value "{value}" (at 0 {h/2 + 1.0:.3f}) (layer "F.Fab")
            (effects (font (size 0.6 0.6) (thickness 0.12)))
            (tstamp {uuid4()}))
        (fp_rect (start {-w/2:.3f} {-h/2:.3f}) (end {w/2:.3f} {h/2:.3f})
            (stroke (width 0.1) (type default)) (fill none) (layer "F.SilkS")
            (tstamp {uuid4()}))
        (fp_rect (start {-w/2 - 0.25:.3f} {-h/2 - 0.25:.3f})
                 (end {w/2 + 0.25:.3f} {h/2 + 0.25:.3f})
            (stroke (width 0.05) (type default)) (fill none) (layer "F.CrtYd")
            (tstamp {uuid4()}))
{chr(10).join(pad_lines)}
    )'''


def _build_edge_cuts(x0: float, y0: float, w: float, h: float) -> str:
    """Board outline as 4 line segments on Edge.Cuts layer (KiCad fab requirement)."""
    pts = [(x0, y0), (x0 + w, y0), (x0 + w, y0 + h), (x0, y0 + h), (x0, y0)]
    lines = []
    for (sx, sy), (ex, ey) in zip(pts[:-1], pts[1:]):
        lines.append(
            f'    (gr_line (start {sx:.3f} {sy:.3f}) (end {ex:.3f} {ey:.3f}) '
            f'(layer "Edge.Cuts") (width 0.15) (tstamp {uuid4()}))'
        )
    return "\n".join(lines)


def _collect_nets(components: list) -> list[str]:
    """Collect unique net names from component pin assignments."""
    seen = set()
    nets = []
    for c in components:
        for net in (c.get("nets") or []):
            n = str(net)
            if n and n not in seen:
                seen.add(n)
                nets.append(n)
    if not nets:
        # Standard nets so the file is non-trivial
        nets = ["GND", "+3V3", "+5V", "VBAT"]
    return nets


def _infer_board(components: list, axis: str) -> float:
    if not components:
        return 50.0
    if axis == "w":
        return max((float(c.get("x_mm", 0)) + float(c.get("width_mm", 0))
                    for c in components), default=50.0) + 2.0
    return max((float(c.get("y_mm", 0)) + float(c.get("height_mm", 0))
                for c in components), default=50.0) + 2.0


# ---------------------------------------------------------------------------
# Optional: Gerber export via kicad-cli (if installed)
# ---------------------------------------------------------------------------

def export_gerbers(kicad_pcb_path: str | Path, out_dir: str | Path | None = None) -> dict:
    """Run `kicad-cli pcb export gerbers` on a .kicad_pcb file. No-op if
    kicad-cli isn't on PATH (returns {'available': False}).

    Returns {'available': bool, 'gerber_dir': path, 'drill_dir': path,
             'files': [...]} so the caller can include outputs in the bundle.
    """
    import shutil
    import subprocess

    cli = shutil.which("kicad-cli") or shutil.which("kicad-cli.exe")
    if not cli:
        return {"available": False, "reason": "kicad-cli not on PATH"}

    kicad_pcb_path = Path(kicad_pcb_path)
    out_dir = Path(out_dir) if out_dir else (kicad_pcb_path.parent / "gerbers")
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        # Gerbers
        subprocess.run(
            [cli, "pcb", "export", "gerbers",
             "--output", str(out_dir),
             str(kicad_pcb_path)],
            check=True, capture_output=True, timeout=60,
        )
        # Drill files
        subprocess.run(
            [cli, "pcb", "export", "drill",
             "--output", str(out_dir),
             str(kicad_pcb_path)],
            check=True, capture_output=True, timeout=60,
        )
        files = sorted(str(f) for f in out_dir.iterdir() if f.is_file())
        return {
            "available": True,
            "gerber_dir": str(out_dir),
            "files": files,
            "n_files": len(files),
        }
    except subprocess.CalledProcessError as exc:
        return {
            "available": True,
            "error": exc.stderr.decode("utf-8", errors="replace")[:500],
        }
    except Exception as exc:
        return {"available": True, "error": f"{type(exc).__name__}: {exc}"}


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python -m aria_os.ecad.kicad_pcb_writer <bom.json> [out.kicad_pcb]")
        sys.exit(1)
    out = write_kicad_pcb(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
    print(f"Wrote {out}")
    g = export_gerbers(out)
    print(f"Gerber export: {g}")
